// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZY8CyJlV9pKPb2_ILkEmOssDtXzyCtc',
    appId: '1:340300919596:web:7b9e796ceef6dc367fb289',
    messagingSenderId: '340300919596',
    projectId: 'windwisherapp-5ed22',
    authDomain: 'windwisherapp-5ed22.firebaseapp.com',
    storageBucket: 'windwisherapp-5ed22.firebasestorage.app',
    measurementId: 'G-VEG885W8YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4cOG3qqS2rKiP9jQhiyH9spw2nKl-qGE',
    appId: '1:340300919596:android:b3d5f3230e2056407fb289',
    messagingSenderId: '340300919596',
    projectId: 'windwisherapp-5ed22',
    storageBucket: 'windwisherapp-5ed22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRYFHff-c9Kae-FEP-iZy8vKC87N69dm4',
    appId: '1:340300919596:ios:f01eef8777aba8497fb289',
    messagingSenderId: '340300919596',
    projectId: 'windwisherapp-5ed22',
    storageBucket: 'windwisherapp-5ed22.firebasestorage.app',
    iosBundleId: 'com.windwisher.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRYFHff-c9Kae-FEP-iZy8vKC87N69dm4',
    appId: '1:340300919596:ios:f01eef8777aba8497fb289',
    messagingSenderId: '340300919596',
    projectId: 'windwisherapp-5ed22',
    storageBucket: 'windwisherapp-5ed22.firebasestorage.app',
    iosBundleId: 'com.windwisher.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZY8CyJlV9pKPb2_ILkEmOssDtXzyCtc',
    appId: '1:340300919596:web:46980cfc4ac557047fb289',
    messagingSenderId: '340300919596',
    projectId: 'windwisherapp-5ed22',
    authDomain: 'windwisherapp-5ed22.firebaseapp.com',
    storageBucket: 'windwisherapp-5ed22.firebasestorage.app',
    measurementId: 'G-243WQN5NLE',
  );
}
